FROM quay.io/Tahul121/rahulmdbot
RUN git clone https://github.com/Tahul121/RAHUL-MD-BOT /root/Tahul121
WORKDIR /root/Tahul121/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
