FROM quay.io/tahul121/rahul-md-bot
RUN git clone https://github.com/Tahul121/RAHUL-MD-BOT /root/Maher-Zubair/RAHUL-MD-BOT
WORKDIR /root/Tahul121/RAHUL-MD-BOT/
RUN npm install npm@latest
RUN npm install
EXPOSE 8000
CMD ["npm", "start"]
 
 
